### PR TITLE
Added parsing of images for RSS items

### PR DESCRIPTION
**Pull request by vgrichina**
Content (or summary if no content) is analyzed for  tags, the URLs of images are then stored in `MWFeedItem.images`

### CODE REVIEW

**Comment by mouezca** [comment]
Hi , 
First thanks for this Great open source
I begin Development iphone and maybe my question is for newbi so my question is : 
i try to get a image to put in cell.imageview.image, this is my code : 

```
    cell.imageView.image=[item.images objectAtIndex:indexPath.row];
```

But the application crach if you can help me 

Thanks

**Comment by vgrichina** [comment]
item.images contains URLs of images, not images themselves, that's why it doesn't work.

To show image given its URL you for example can use Network Image from Nimbus framework – http://latest.docs.nimbuskit.info/group___nimbus_network_image.html

**Comment by mwaterfall** [comment]
@vgrichina Thanks for this pull request. I'm going to be implementing image parsing soon but in a slightly different way. Check back soon!

**Comment by exposeapps** [comment]
How could I edit this so that it can pull-in thumbnail images from youtube feeds? It works well for many feeds but for youtube it isn't working.

**Comment by vgrichina** [comment]
@exposeapps can you give a link to example feed? Also I see two possible variants:
- images are represented as enclosures, not inside of HTML content
- HTML content isn't valid XHTML

**Comment by exposeapps** [comment]
@vgrichina Here you go: http://gdata.youtube.com/feeds/api/videos?q=Los+Angeles&start-index=1&max-results=50&v=2

I appreciate your quick reply! Thank you very much!

**Comment by musikito** [comment]
hey @vgrichina, great coding man. But I seem to be having a problem; when I try to use the array(item.images.count) it shows that there's one element on it, this causes the app. to quit with an array out of bounds.
I've save the array to a Plist and it only shows the last element(image), not the whole array. any thoughts?

**Comment by vgrichina** [comment]
@exposeapps looks like your feed doesn't have images in it

**Comment by vgrichina** [comment]
@musikito can you show some code example so that I better understand what you mean? E.g. as a Gist.

**Comment by musikito** [comment]
@vgrichina thank you for that fast response. I use the arrary from the "cellForRowAtIndexPath" and below is the output of the NSLog, as you can see the count is alway 1, although it's outputing the images that really are on the web.
The only image that always appear in the app is the first one, after that it goes beyond bounds.

// Customize the appearance of table view cells.
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
  static NSString *CellIdentifier = @"Cell";
  
  UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
  if (cell == nil)
  {
      cell = [[[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CellIdentifier]autorelease];
  } 
  
  MWFeedItem *item = [itemsToDisplay objectAtIndex:indexPath.row];
     if ([item.images count] > 0 ) {
    //  _objects = [[NSMutableArray alloc] initWithArray:item.images];
    //  _objects = [NSArray arrayWithObject:item.images];
      NSLog(@"there is images %@/%d",_objects,[item.images count]);
  
  cell.textLabel.text = [NSString stringWithFormat:@"Image #%d", indexPath.row];
      @try {
          [cell.imageView setImageWithURL:[NSURL URLWithString:[item.images objectAtIndex:indexPath.row]] placeholderImage:[UIImage imageNamed:@"Icon.png"]];
      }
      @catch (NSException *exception) {
         NSLog(@"Error no image at: %@", exception.debugDescription);
     } 
  } //endif
    return cell;
  }

here's the output of the NSLog:
2012-06-27 19:57:51.695 Musikita[26159:207] Started Parsing: http://feeds.feedburner.com/TuMusicaLatinaTanLatinaComoTu
2012-06-27 19:57:51.749 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:51.773 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:51.797 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:51.851 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:51.871 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:51.893 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:51.944 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:51.964 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:51.982 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.022 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.043 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.064 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.088 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.106 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.124 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.149 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.168 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.188 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.210 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:52.228 Musikita[26159:207] Parsed Feed Info: “Tu Musica latina, tan latina como tu”
2012-06-27 19:57:52.317 Musikita[26159:207] imagenes aqui (
    "http://upload.wikimedia.org/wikipedia/en/d/d8/Mi_Vida_eres_Tu.jpg"
) 1
2012-06-27 19:57:52.655 Musikita[26159:207] imagenes aqui (
    "http://upload.wikimedia.org/wikipedia/en/d/d8/Mi_Vida_eres_Tu.jpg"
) 1
2012-06-27 19:57:53.009 Musikita[26159:207] imagenes aqui (
    "http://upload.wikimedia.org/wikipedia/en/d/d8/Mi_Vida_eres_Tu.jpg"
) 1
2012-06-27 19:57:53.045 Musikita[26159:207] Parsed Feed Item: “Los Temerarios anuncian un sencillo como adelanto de su nuevo disco”
2012-06-27 19:57:53.103 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:53.350 Musikita[26159:207] imagenes aqui (
    "http://tumusicalatina.com/Data/Sites/1/media/maffio.jpg"
) 1
2012-06-27 19:57:53.514 Musikita[26159:207] imagenes aqui (
    "http://tumusicalatina.com/Data/Sites/1/media/maffio.jpg"
) 1
2012-06-27 19:57:53.587 Musikita[26159:207] imagenes aqui (
    "http://tumusicalatina.com/Data/Sites/1/media/maffio.jpg"
) 1
2012-06-27 19:57:53.627 Musikita[26159:207] Parsed Feed Item: “Maffio invade el verano con “Mi Sonido””
2012-06-27 19:57:53.829 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:53.881 Musikita[26159:207] imagenes aqui (
    "http://ecx.images-amazon.com/images/I/61DmHXWgFHL._SL300_.jpg"
) 1
2012-06-27 19:57:54.114 Musikita[26159:207] imagenes aqui (
    "http://ecx.images-amazon.com/images/I/61DmHXWgFHL._SL300_.jpg"
) 1
2012-06-27 19:57:54.175 Musikita[26159:207] imagenes aqui (
    "http://ecx.images-amazon.com/images/I/61DmHXWgFHL._SL300_.jpg"
) 1
2012-06-27 19:57:54.291 Musikita[26159:207] Parsed Feed Item: “Alejandro Sanz estrena “No me compares” (Video)”
2012-06-27 19:57:54.387 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:54.716 Musikita[26159:207] imagenes aqui (
    "http://img.zemanta.com/zemified_e.png?x-id=7b931ac2-cb16-44da-b915-3081a509224d"
) 1
2012-06-27 19:57:54.753 Musikita[26159:207] imagenes aqui (
    "http://img.zemanta.com/zemified_e.png?x-id=7b931ac2-cb16-44da-b915-3081a509224d"
) 1
2012-06-27 19:57:54.816 Musikita[26159:207] imagenes aqui (
    "http://img.zemanta.com/zemified_e.png?x-id=7b931ac2-cb16-44da-b915-3081a509224d"
) 1
2012-06-27 19:57:54.860 Musikita[26159:207] Parsed Feed Item: “Thalía tendrá su estrella en el Paseo de la Fama en Hollywood”
2012-06-27 19:57:54.991 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:55.041 Musikita[26159:207] imagenes aqui (
    "http://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Fernando_Villalona_adjusted.jpg/300px-Fernando_Villalona_adjusted.jpg"
) 1
2012-06-27 19:57:55.103 Musikita[26159:207] imagenes aqui (
    "http://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Fernando_Villalona_adjusted.jpg/300px-Fernando_Villalona_adjusted.jpg"
) 1
2012-06-27 19:57:55.196 Musikita[26159:207] imagenes aqui (
    "http://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Fernando_Villalona_adjusted.jpg/300px-Fernando_Villalona_adjusted.jpg"
) 1
2012-06-27 19:57:55.260 Musikita[26159:207] Parsed Feed Item: “Fernando Villalona: entre invitados, bolero y urbano”
2012-06-27 19:57:55.301 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:55.339 Musikita[26159:207] imagenes aqui (
    "http://farm4.static.flickr.com/3179/2363434859_0a80c2c02e_m.jpg"
) 1
2012-06-27 19:57:55.382 Musikita[26159:207] imagenes aqui (
    "http://farm4.static.flickr.com/3179/2363434859_0a80c2c02e_m.jpg"
) 1
2012-06-27 19:57:55.465 Musikita[26159:207] imagenes aqui (
    "http://farm4.static.flickr.com/3179/2363434859_0a80c2c02e_m.jpg"
) 1
2012-06-27 19:57:55.508 Musikita[26159:207] Parsed Feed Item: “Wilfrido Vargas : "El merengue no sabe lo que es crisis"”
2012-06-27 19:57:55.590 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:55.615 Musikita[26159:207] imagenes aqui (
) 0
2012-06-27 19:57:55.774 Musikita[26159:207] imagenes aqui (
) 0
2012-06-27 19:57:55.838 Musikita[26159:207] imagenes aqui (
) 0
2012-06-27 19:57:55.884 Musikita[26159:207] Parsed Feed Item: “Daddy Yankee nos presenta su pasarela (video)”
2012-06-27 19:57:56.006 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:56.085 Musikita[26159:207] imagenes aqui (
    "http://tumusicalatina.com/Data/Sites/1/media/merengue.jpg"
) 1
2012-06-27 19:57:56.117 Musikita[26159:207] imagenes aqui (
    "http://tumusicalatina.com/Data/Sites/1/media/merengue.jpg"
) 1
2012-06-27 19:57:56.185 Musikita[26159:207] imagenes aqui (
    "http://tumusicalatina.com/Data/Sites/1/media/merengue.jpg"
) 1
2012-06-27 19:57:56.288 Musikita[26159:207] Parsed Feed Item: “Hay o no hay crisis en el Merengue?”
2012-06-27 19:57:56.686 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:56.783 Musikita[26159:207] imagenes aqui (
    "http://tumusicalatina.blogs.com/.a/6a00d83451bf4569e2016767b0f139970b-800wi"
) 1
2012-06-27 19:57:56.973 Musikita[26159:207] imagenes aqui (
    "http://tumusicalatina.blogs.com/.a/6a00d83451bf4569e2016767b0f139970b-800wi"
) 1
2012-06-27 19:57:57.043 Musikita[26159:207] imagenes aqui (
    "http://tumusicalatina.blogs.com/.a/6a00d83451bf4569e2016767b0f139970b-800wi"
) 1
2012-06-27 19:57:57.119 Musikita[26159:207] Parsed Feed Item: “Maffio considera El merengue está en su mejor momento”
2012-06-27 19:57:57.246 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:57.315 Musikita[26159:207] imagenes aqui (
    "http://farm4.static.flickr.com/3161/2813721156_1a055687f1_m.jpg"
) 1
2012-06-27 19:57:57.369 Musikita[26159:207] imagenes aqui (
    "http://farm4.static.flickr.com/3161/2813721156_1a055687f1_m.jpg"
) 1
2012-06-27 19:57:57.506 Musikita[26159:207] imagenes aqui (
    "http://farm4.static.flickr.com/3161/2813721156_1a055687f1_m.jpg"
) 1
2012-06-27 19:57:57.649 Musikita[26159:207] Parsed Feed Item: “La lluvia no paró la fiesta de Juan Luis Guerra”
2012-06-27 19:57:57.748 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:57.821 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:57.849 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:57.883 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:57.968 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:57.995 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:58.080 Musikita[26159:207] imagenes aqui (null) 0
2012-06-27 19:57:58.097 Musikita[26159:207] Finished Parsing
2012-06-27 19:57:58.125 Musikita[26159:207] there is images (
)/1
2012-06-27 19:57:58.209 Musikita[26159:207] there is images (
)/1
2012-06-27 19:57:58.231 Musikita[26159:207] Error no image at: **\* -[__NSArrayI objectAtIndex:]: index 1 beyond bounds [0 .. 0]
2012-06-27 19:57:58.679 Musikita[26159:207] there is images (
)/1
2012-06-27 19:57:58.700 Musikita[26159:207] Error no image at: **\* -[__NSArrayI objectAtIndex:]: index 2 beyond bounds [0 .. 0]
2012-06-27 19:57:58.744 Musikita[26159:207] there is images (
)/1
2012-06-27 19:57:59.012 Musikita[26159:207] Error no image at: **\* -[__NSArrayI objectAtIndex:]: index 3 beyond bounds [0 .. 0]
2012-06-27 19:57:59.457 Musikita[26159:207] there is images (
)/1
2012-06-27 19:57:59.477 Musikita[26159:207] Error no image at: **\* -[__NSArrayI objectAtIndex:]: index 4 beyond bounds [0 .. 0]
2012-06-27 19:57:59.495 Musikita[26159:207] there is images (
)/1
2012-06-27 19:57:59.551 Musikita[26159:207] Error no image at: **\* -[__NSArrayI objectAtIndex:]: index 5 beyond bounds [0 .. 0]
2012-06-27 19:57:59.758 Musikita[26159:207] there is images (
)/1
2012-06-27 19:57:59.773 Musikita[26159:207] Error no image at: **\* -[__NSArrayI objectAtIndex:]: index 7 beyond bounds [0 .. 0]
2012-06-27 19:57:59.879 Musikita[26159:207] there is images (
)/1
2012-06-27 19:57:59.949 Musikita[26159:207] Error no image at: **\* -[__NSArrayI objectAtIndex:]: index 8 beyond bounds [0 .. 0]
2012-06-27 19:57:59.971 Musikita[26159:207] there is images (
)/1
2012-06-27 19:57:59.992 Musikita[26159:207] Error no image at: **\* -[__NSArrayI objectAtIndex:]: index 9 beyond bounds [0 .. 0]

**Pull request closed without merging**
