### PR TITLE
Quick Format change

### PR DESCRIPTION
**Pull request by sbentzen**
Quickly changed the %C to %d as it was giving me the following error.

Format specifies type 'unsigned short' but the argument has type 'int'

### CODE REVIEW

**Comment by hpique** [comment]
+1

**Comment by jsumners** [comment]
Not sure this patch is an actual fix, but it certainly gets rid of the warnings.

**Comment by jdashmusic** [comment]
Changing it from %C to %d will break the item summary. It causes some of the characters to disappear for some reason.

**Comment by eviltrout** [comment]
:+1:

**Comment by mwaterfall** [comment]
This warning has now been fixed.

**Pull request closed without merging**
